# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FggDataService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FggDataService.proto',
  package='fgg.grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x46ggDataService.proto\x12\x08\x66gg.grpc\"%\n\x06params\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"1\n\x04keys\x12\x0e\n\x06\x66romdt\x18\x01 \x01(\x05\x12\x0c\n\x04todt\x18\x02 \x01(\x05\x12\x0b\n\x03key\x18\x03 \x01(\x05\"k\n\x06\x46ggMsg\x12\x0f\n\x07request\x18\x01 \x01(\x05\x12\x0e\n\x06outkey\x18\x02 \x03(\x05\x12 \n\x06values\x18\x03 \x03(\x0b\x32\x10.fgg.grpc.params\x12\x1e\n\x06relkey\x18\x04 \x03(\x0b\x32\x0e.fgg.grpc.keys\"v\n\x07\x46ggData\x12\r\n\x05\x66ield\x18\x01 \x01(\x05\x12\x13\n\tint_value\x18\x02 \x01(\x05H\x00\x12\x14\n\nlong_value\x18\x03 \x01(\x03H\x00\x12\x13\n\tdbl_value\x18\x04 \x01(\x01H\x00\x12\x13\n\tstr_value\x18\x05 \x01(\tH\x00\x42\x07\n\x05value2\xad\x01\n\x0e\x46ggDataService\x12\x34\n\x0brequestData\x12\x10.fgg.grpc.FggMsg\x1a\x11.fgg.grpc.FggData0\x01\x12\x34\n\x0bpersistData\x12\x11.fgg.grpc.FggData\x1a\x10.fgg.grpc.FggMsg(\x01\x12/\n\tqueryData\x12\x10.fgg.grpc.FggMsg\x1a\x10.fgg.grpc.FggMsgb\x06proto3')
)




_PARAMS = _descriptor.Descriptor(
  name='params',
  full_name='fgg.grpc.params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='fgg.grpc.params.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='fgg.grpc.params.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=71,
)


_KEYS = _descriptor.Descriptor(
  name='keys',
  full_name='fgg.grpc.keys',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromdt', full_name='fgg.grpc.keys.fromdt', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='todt', full_name='fgg.grpc.keys.todt', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='fgg.grpc.keys.key', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=122,
)


_FggMsg = _descriptor.Descriptor(
  name='FggMsg',
  full_name='fgg.grpc.FggMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='fgg.grpc.FggMsg.request', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outkey', full_name='fgg.grpc.FggMsg.outkey', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='fgg.grpc.FggMsg.values', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relkey', full_name='fgg.grpc.FggMsg.relkey', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=231,
)


_FggData = _descriptor.Descriptor(
  name='FggData',
  full_name='fgg.grpc.FggData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='fgg.grpc.FggData.field', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='fgg.grpc.FggData.int_value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long_value', full_name='fgg.grpc.FggData.long_value', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dbl_value', full_name='fgg.grpc.FggData.dbl_value', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_value', full_name='fgg.grpc.FggData.str_value', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='fgg.grpc.FggData.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=233,
  serialized_end=351,
)

_FggMsg.fields_by_name['values'].message_type = _PARAMS
_FggMsg.fields_by_name['relkey'].message_type = _KEYS
_FggData.oneofs_by_name['value'].fields.append(
  _FggData.fields_by_name['int_value'])
_FggData.fields_by_name['int_value'].containing_oneof = _FggData.oneofs_by_name['value']
_FggData.oneofs_by_name['value'].fields.append(
  _FggData.fields_by_name['long_value'])
_FggData.fields_by_name['long_value'].containing_oneof = _FggData.oneofs_by_name['value']
_FggData.oneofs_by_name['value'].fields.append(
  _FggData.fields_by_name['dbl_value'])
_FggData.fields_by_name['dbl_value'].containing_oneof = _FggData.oneofs_by_name['value']
_FggData.oneofs_by_name['value'].fields.append(
  _FggData.fields_by_name['str_value'])
_FggData.fields_by_name['str_value'].containing_oneof = _FggData.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['params'] = _PARAMS
DESCRIPTOR.message_types_by_name['keys'] = _KEYS
DESCRIPTOR.message_types_by_name['FggMsg'] = _FggMsg
DESCRIPTOR.message_types_by_name['FggData'] = _FggData
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

params = _reflection.GeneratedProtocolMessageType('params', (_message.Message,), dict(
  DESCRIPTOR = _PARAMS,
  __module__ = 'FggDataService_pb2'
  # @@protoc_insertion_point(class_scope:fgg.grpc.params)
  ))
_sym_db.RegisterMessage(params)

keys = _reflection.GeneratedProtocolMessageType('keys', (_message.Message,), dict(
  DESCRIPTOR = _KEYS,
  __module__ = 'FggDataService_pb2'
  # @@protoc_insertion_point(class_scope:fgg.grpc.keys)
  ))
_sym_db.RegisterMessage(keys)

FggMsg = _reflection.GeneratedProtocolMessageType('FggMsg', (_message.Message,), dict(
  DESCRIPTOR = _FggMsg,
  __module__ = 'FggDataService_pb2'
  # @@protoc_insertion_point(class_scope:fgg.grpc.FggMsg)
  ))
_sym_db.RegisterMessage(FggMsg)

FggData = _reflection.GeneratedProtocolMessageType('FggData', (_message.Message,), dict(
  DESCRIPTOR = _FggData,
  __module__ = 'FggDataService_pb2'
  # @@protoc_insertion_point(class_scope:fgg.grpc.FggData)
  ))
_sym_db.RegisterMessage(FggData)



_FggDataSERVICE = _descriptor.ServiceDescriptor(
  name='FggDataService',
  full_name='fgg.grpc.FggDataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=354,
  serialized_end=527,
  methods=[
  _descriptor.MethodDescriptor(
    name='requestData',
    full_name='fgg.grpc.FggDataService.requestData',
    index=0,
    containing_service=None,
    input_type=_FggMsg,
    output_type=_FggData,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='persistData',
    full_name='fgg.grpc.FggDataService.persistData',
    index=1,
    containing_service=None,
    input_type=_FggData,
    output_type=_FggMsg,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='queryData',
    full_name='fgg.grpc.FggDataService.queryData',
    index=2,
    containing_service=None,
    input_type=_FggMsg,
    output_type=_FggMsg,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FggDataSERVICE)

DESCRIPTOR.services_by_name['FggDataService'] = _FggDataSERVICE

# @@protoc_insertion_point(module_scope)
